apiVersion: v1
kind: ConfigMap
metadata:
  name: kwok-provider-config
  namespace: kube-system
data:
  config: |
    apiVersion: v1alpha1
    readNodesFrom: configmap
    nodegroups:
      fromNodeLabelKey: "recluster.io/node-group"
    nodes:
      skipTaint: true
    configmap:
      name: kwok-provider-templates
      key: templates
