---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recluster.io
  resources:
  - rcnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - recluster.io
  resources:
  - rcnodes/finalizers
  verbs:
  - update
- apiGroups:
  - recluster.io
  resources:
  - rcnodes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - recluster.io
  resources:
  - rcpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - recluster.io
  resources:
  - rcpolicies/status
  verbs:
  - get
